devices:
- input_name: 'AT Translated Set 2 keyboard'
  input_fn: '/dev/input/event4'
  output_name: remap-kbd
  remappings:
    # Emits predefined number of key strokes
    KEY_LEFTSHIFT:
    - code: KEY_A
      value: [1,0]
      repeat: true
      count: 6
    # Same as above
    KEY_RIGHTSHIFT:
    - code: KEY_A
      value: [1,0,1,0]
      repeat: true
      count: 3
    # Emits key strokes as long as ALT is pressed
    KEY_LEFTALT:
    - code: KEY_A
      value: [1,0,1,0]
      repeat: true
- input_name: 'Compx 2.4G Receiver'
  input_fn: '/dev/input/event7'
  output_name: remap-mouse
  remappings:
    BTN_RIGHT:
    - code: BTN_LEFT
      value: [1, 0]
      repeat: true
      count: 2
    BTN_EXTRA:
    - code: REL_WHEEL
      type: EV_REL
      value: 1
      repeat: true
      rate: .1
      rate: 0.3
    BTN_SIDE:
    - code: REL_WHEEL
      type: EV_REL
      value: -1
      repeat: true
      rate: .1
