devices:
# - input_name: 'AT Translated Set 2 keyboard'
#   input_phys: 'isa0060/serio0/input0'
#   output_name: remap-kbd
#   remappings:
#     KEY_CAPSLOCK:
#     - KEY_Z
- input_name: 'Compx 2.4G Receiver'
  input_phys: 'usb-0000:00:1d.0-1.2/input1'
  output_name: remap-mouse
  remappings:
    BTN_EXTRA:
    - REL_WHEEL
    - KEY_A
    BTN_SIDE:
    - KEY_C
