devices:
- input_name: 'AT Translated Set 2 keyboard'
  input_fn: '/dev/input/event4'
  output_name: remap-kbd
  remappings:
    KEY_LEFTSHIFT:
    - code: KEY_A
      ignore_depress: true
      value: [1,0]
      repeat: true
      count: 3
    KEY_CAPSLOCK:
    - KEY_Z
    - code: KEY_C
- input_name: 'Compx 2.4G Receiver'
  input_fn: '/dev/input/event6'
  output_name: remap-mouse
  remappings:
    BTN_MIDDLE:
    - code: BTN_LEFT
      value: [1, 0]
      repeat: true
      count: 2
      ignore_depress: true
      rate: .1
    BTN_LEFT:
    - code: BTN_LEFT
      value: [1, 0]
      repeat: true
      count: 2
      rate: .2
    BTN_EXTRA:
    - code: REL_WHEEL
      type: EV_REL
      value: 1
      repeat: true
      rate: .1
    BTN_SIDE:
    - code: REL_WHEEL
      type: EV_REL
      value: -1
      repeat: true
      rate: .1
