devices:
# - input_name: 'AT Translated Set 2 keyboard'
#   input_phys: 'isa0060/serio0/input0'
#   output_name: remap-kbd
#   remappings:
#     KEY_CAPSLOCK:
#     - KEY_Z
- input_name: 'Compx 2.4G Receiver'
  output_name: remap-mouse
  remappings:
    BTN_EXTRA:
    - code: REL_WHEEL
      type: EV_REL
      value: 1
    BTN_SIDE:
    - KEY_C
