devices:
# - input_name: 'AT Translated Set 2 keyboard'
#   input_phys: 'isa0060/serio0/input0'
#   output_name: remap-kbd
#   remappings:
#     KEY_CAPSLOCK:
#     - KEY_Z
#     - code: KEY_C
- input_name: 'Compx 2.4G Receiver'
  input_fn: '/dev/input/event6'
  output_name: remap-mouse
  remappings:
    # BTN_LEFT:
    # - KEY_A
    BTN_LEFT:
    # - code: REL_WHEEL
    #   type: EV_REL
    #   value: 1
    #   repeat: .1
    # - code: KEY_A
    - code: BTN_LEFT
      # type: EV_KEY
      value: [1, 0]
      repeat: true
      count: 2
      # ignore_depress: true
      rate: .2
    BTN_SIDE:
    - code: REL_WHEEL
      type: EV_REL
      value: -1
      repeat: true
      rate: .1
