devices:
- input_name: 'Compx 2.4G Receiver'
  input_fn: '/dev/input/event7'
  output_name: remap-mouse
  remappings:
    #    left double click on right long click
    BTN_RIGHT:
    - code: BTN_RIGHT
      long_press:
        duration: .2
        value: [1, 0] # EV_KEY events - 1: key down, 0: key up
        code: BTN_LEFT
        repeat: true
        rate: .1
        count: 2
      value: [1, 0] # EV_KEY events - 1: key down, 0: key up
#    left click on right long click
    BTN_RIGHT:
    - code: BTN_RIGHT
      long_press:
        duration: .2
        value: [1, 0] # EV_KEY events - 1: key down, 0: key up
        code: BTN_LEFT
      value: [1, 0] # EV_KEY events - 1: key down, 0: key up
#    move up on long click
    BTN_RIGHT:
    - code: BTN_RIGHT
      long_press:
        duration: .2
        value: 1 # EV_KEY events - 1: key down, 0: key up
        code: REL_WHEEL
        type: EV_REL
#    right click on right long press, left click on right short press
    BTN_RIGHT:
    - code: BTN_LEFT
      long_press:
        duration: .2
        code: BTN_RIGHT
        value: [1, 0] # EV_KEY events - 1: key down, 0: key up
#    scroll on right long press
    BTN_SIDE:
    - code: BTN_SIDE
      long_press:
        duration: .15
        value: [-1] # EV_KEY events - 1: key down, 0: key up
        code: REL_WHEEL
        type: EV_REL
        repeat: true
    BTN_EXTRA:
    - code: BTN_EXTRA
      long_press:
        duration: .15
        value: [1] # EV_KEY events - 1: key down, 0: key up
        code: REL_WHEEL
        type: EV_REL
        repeat: true


    BTN_RIGHT:
    - code: BTN_LEFT
      long_press_duration: .5
      long_press_value: [1, 0] # EV_KEY events - 1: key down, 0: key up
      long_press_code: BTN_RIGHT
      value: [1, 0] # EV_KEY events - 1: key down, 0: key up
