devices:
# Mouse scroll
- input_name: 'Compx 2.4G Receiver'
  input_phys: 'usb-0000:00:14.0-3/input1'
  output_name: remap-mouse
  remappings:
    # Map right button to double click when long pressed
    BTN_RIGHT:
    - code: BTN_RIGHT
      long_press:
        duration: .2
        code: BTN_LEFT
        repeat: true
        rate: .1
        count: 2
    # Map side buttons to vertical scroll
    # Scroll event is repeated as long as button is kept pressed.
    # Original behaviour (back/forward) is kept for short click.
    BTN_SIDE:
    - code: BTN_SIDE
      long_press:
        duration: .15
        value: [-1]
        code: REL_WHEEL
        type: EV_REL
        repeat: true
    BTN_EXTRA:
    - code: BTN_EXTRA
      long_press:
        duration: .15
        value: [1]
        code: REL_WHEEL
        type: EV_REL
        repeat: true
- input_name: 'AT Translated Set 2 keyboard'
  input_phys: 'isa0060/serio0/input0'
  output_name: remap-asus-kb
  remappings:
    # Map TAB to paste when long pressed. Original behaviour remains on short press.
    KEY_TAB:
      - code: KEY_TAB
        long_press:
          code: [KEY_LEFTCTRL, KEY_V]
    # Map F1 to copy when long pressed. Original behaviour remains on long press.
    KEY_F1:
      - code: [KEY_LEFTCTRL, KEY_C]
        long_press:
          code: KEY_F1








devices:
- input_name: 'Compx 2.4G Receiver'
  input_fn: '/dev/input/event7'
  output_name: remap-mouse
  remappings:
    #    left double click on right long click
    BTN_RIGHT:
    - code: BTN_RIGHT
      long_press:
        duration: .2
        code: BTN_LEFT
        repeat: true
        rate: .1
        count: 2
#    left click on right long click
    BTN_RIGHT:
    - code: BTN_RIGHT
      long_press:
        duration: .2
        code: BTN_LEFT
#    move up on long click
    BTN_RIGHT:
    - code: BTN_RIGHT
      long_press:
        duration: .2
        value: 1 # EV_KEY events - 1: key down, 0: key up
        code: REL_WHEEL
        type: EV_REL
#    right click on right long press, left click on right short press
    BTN_RIGHT:
    - code: BTN_LEFT
      long_press:
        duration: .2
        code: BTN_RIGHT
#    scroll on right long press
    BTN_SIDE:
    - code: BTN_SIDE
      long_press:
        duration: .15
        value: [-1]
        code: REL_WHEEL
        type: EV_REL
        repeat: true
    BTN_EXTRA:
    - code: BTN_EXTRA
      long_press:
        duration: .15
        value: [1]
        code: REL_WHEEL
        type: EV_REL
        repeat: true
    # paste
    BTN_RIGHT:
    - code: BTN_RIGHT
      long_press:
        duration: .2
        code: [KEY_LEFTCTRL, KEY_V]


    BTN_RIGHT:
    - code: BTN_LEFT
      long_press_duration: .5
      long_press_value: [1, 0] # EV_KEY events - 1: key down, 0: key up
      long_press_code: BTN_RIGHT
      value: [1, 0] # EV_KEY events - 1: key down, 0: key up
